services:
  note-service:
    extends:
      file: compose.yml
      service: note-service
    image: virabshetkar/note-service:debug
    build:
      context: .
      target: debug
    environment:
      - ASPNETCORE_URLS=http://+:8080 # '+' is required for host binding 
      - ASPNETCORE_ENVIRONMENT=Local
      - USE_REMOTE_CONFIG=false
      - REMOTE_CONFIG_URL=http://reverse-proxy/config/services/note-service/ # Trailing slash is required
      - WAIT_FOR_DEBUGGER=true # Required when debugging else turn this off 
    ports:
      - 5001:8080
    networks:
      - local-debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./bin/Debug/net9.0/publish:/app/:ro
    command: [ "Service.Note.dll" ]

networks:
  local-debug:
    external: true
